apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gatekeeper
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"

spec:
  generators:
    - git:
        repoURL: https://github.com/nagarajurahul/gitops-platform
        revision: main
        files:
          - path: config/clusters.yaml
  template:
    metadata:
      name: gatekeeper-{{name}}-{{env}}
    spec:
      project: platform

      destination:
        name: "{{clusterName}}" # cluster name registered in Argo CD
        namespace: gatekeeper-system

      source:
        repoURL: https://github.com/nagarajurahul/helm-charts
        targetRevision: main
        path: gatekeeper

        helm:
          valueFiles:
            - values.yaml
            - values-enforce.yaml

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
